[package]
name = "viarableBinding"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1_12"
path = "src/1_12.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
